### PR TITLE
SSM Parameter Store support

### LINKED ISSUE #86: Support for Parameter Store
Now that AWS parameter store has the option for increased API rates, are there any plans to support it?

### PR DESCRIPTION
**Pull request by tmxak**
this commit fixes #86

### CODE REVIEW

**Comment by jeffpearce** [comment]
Optionally, if you have time to update the docs and provide an example secret, it would be appreciated. If not, I'll update after it's merged

**Comment by tmxak** [comment]
> Thanks for the PR! Could you fix the failing test as well?
> Optionally, if you have time to update the docs and provide an example secret, it would be appreciated. If not, I'll update after it's merged
Sure. No problem. I will update the docs and add an example. You have an existing example "awssm-key-value-example.yaml" which is not an ssm example and I will rename it

**Comment by tmxak** [comment]
This PR is ready to be merged.

**Comment by jeffpearce** [comment]
Thanks for the PR @tmxak!

**Comment by Sytten** [comment]
Thanks for the update! @jeffpearce is there a planned release? I would like to use it asap :)

**Comment by jeffpearce** [comment]
Hi @Sytten - we included this with `godaddy/kubernetes-external-secrets:1.3.1`

**Comment by sethatron** [comment]
Could the README be updated? The section https://github.com/godaddy/kubernetes-external-secrets#backends still says kubernetes-external-secrets only supports AWS Secrets Manager

**Pull request merged**
