### PR TITLE
Pass in the Web Identity token to assumeRoleWithWebIdentity

### PR DESCRIPTION
**Pull request by dalgibbard**
In relation to #254 - the recent changes don't appear to be working on EKS Fargate for me, and the AWS SDK documentation suggest you should provide the token into the ```assumeRoleWithWebIdentity``` method params.

Update: confirmed that the current master branch with WebIdentities results in an error because the web token is a required param: https://github.com/godaddy/kubernetes-external-secrets/issues/254#issuecomment-652351266

This change reads the token contents and passes them in.

### CODE REVIEW

**Comment by dalgibbard** [comment]
@Flydiverny could I trouble you to review this when you get a mo? :)

**Comment by Flydiverny** [comment]
@dalgibbard thanks for taking your time with this :)

**Comment by dalgibbard** [comment]
Thanks a lot @Flydiverny ! Do you know when this is likely to make it into a release version? :)

**Comment by Flydiverny** [comment]
@dalgibbard I pinged @silasbw on slack asking for a release

**Pull request merged**
