### PR TITLE
Support for GCP Secret Manager

### PR DESCRIPTION
**Pull request by karan-kap**
This PR has changes to support GCP Secret Manager as a backend.

### CODE REVIEW

**Comment by inductor** [comment]
@karan-kap Did you have a look at this? https://github.com/godaddy/kubernetes-external-secrets/pull/288

**Comment by karan-kap** [comment]
Ah! seems like I missed it.

Nevermind, I looked at pull request 288, mostly the changes are similar, a small point though, the example in that PR passes the complete path of the key (including the projectId), whereas this can be obtained from the SecretManagerServiceClient.

**Comment by wapa5pow** [comment]
I am looking for secret manager tool for k8s. "kubernetes-external-secrets" seems good for me to use secret manager on GKE with this pull request, so I tested it on my GKE cluster.

I works well with the following logs. I hope this pull request will be merged soon. 

```
+ external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz › kubernetes-external-secrets
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets npm info it worked if it ends with ok
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets npm WARN npm npm does not support Node.js v12.13.0
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets npm WARN npm You should probably upgrade to a newer version of node as we
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets npm WARN npm can't make any promises that npm will work with this version.
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets npm WARN npm You can find the latest version at https://nodejs.org/
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets npm info using npm@6.4.1
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets npm info using node@v12.13.0
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets npm info lifecycle kubernetes-external-secrets@3.0.0~prestart: kubernetes-external-secrets@3.0.0
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets npm info lifecycle kubernetes-external-secrets@3.0.0~start: kubernetes-external-secrets@3.0.0
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets 
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets > kubernetes-external-secrets@3.0.0 start /app
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets > ./bin/daemon.js
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets 
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585194950440,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"loading kube specs","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585194950627,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"successfully loaded kube specs","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585194950627,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"updating CRD","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585194950627,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"Upserting custom resource externalsecrets.kubernetes-client.io","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585194950646,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"successfully updated CRD","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585194950650,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"starting app","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585194950655,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"successfully started app","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585194950655,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"MetricsServer listening on port 3001","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets Thu, 26 Mar 2020 03:55:50 GMT kubernetes-client deprecated .getStream use .getObjectStream, see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md at lib/external-secret.js:40:10




external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585195168960,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"starting poller for default/k8s-secret-test","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585195168969,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"running poll on the secret default/k8s-secret-test","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets secret created successfully for key [k8s-secret-test]
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585195169363,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"upserting secret default/k8s-secret-test","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585195169378,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"stopping poller for default/k8s-secret-test","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585195169379,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"starting poller for default/k8s-secret-test","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585195174447,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"stopping poller for default/k8s-secret-test","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585195174453,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"starting poller for default/k8s-secret-test","v":1}
external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz kubernetes-external-secrets {"level":30,"time":1585195179372,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-6c89c67cf-g7jxz","msg":"running poll on the secret default/k8s-secret-test","v":1}
...
```

**Comment by silasbw** [comment]
Handled by https://github.com/godaddy/kubernetes-external-secrets/pull/288.  Looks like there was a race with this PR.  Thank you @karan-kap for contributing this PR.  Did you want to consider adding a change based on your comment here: https://github.com/godaddy/kubernetes-external-secrets/pull/301#issuecomment-600196766 ?

**Comment by pydevops** [comment]
This PR support GKE's workload identity and it works well. I try to accomplish same with https://github.com/godaddy/kubernetes-external-secrets/pull/288, now merged into master branch but with no clue how to configure it.  
The example https://github.com/godaddy/kubernetes-external-secrets/blob/master/examples/gcpsecretsmanager-example%20copy.yaml shows we have to configure key such as "projects/111122223333/secrets/my-secret/versions/latest", while in the current PR, key is simply "my-secret", it is a lot simple and easy to fit into multiple projects without templating for different projects (a.k.a environment).

**Comment by karan-kap** [comment]
@silasbw - will submit another PR shortly to build the URI with-in the _get method of GCP Secret Manager Backend. Version can be passed as keyOption, if it present then fetch that version, else fetch the latest version.

**Pull request closed without merging**
