### PR TITLE
Fix link to kubernetes auth method

### PR DESCRIPTION
**Pull request by dj80hd**

### CODE REVIEW

**Comment by dj80hd** [comment]
How do I make the "E2E" and "Node 12" checks run ?

**Comment by Flydiverny** [comment]
I've pinged silasbw on slack and hopefully he gets some time to look at the CI issue.

**Comment by Flydiverny** [comment]
#350 should hopefully fix it, not sure how to trigger it here tho, might be easiest to just create a new PR.

**Comment by dj80hd** [comment]
thanks @Flydiverny - I was able to get them to run with a upstream rebase and force push.

**Pull request merged**
