### PR TITLE
chore(sec2kes): script to convert a Secret to an ExternalSecret + AWS SM entries

### PR DESCRIPTION
**Pull request by silasbw**
You would do something like:

```
kubectl -n simple-service get secret simple-service -o json > simple-service.json
mkdir simple-service-things
node bin/sec2kes.js --input simple-service.json --ouput simple-service-things
```

And then follow the instructions logged to the console. They would be something like:

```
aws secretsmanager create-secret  --name simple-service/service-account --secret-string file://simple-service-things/service-account.json
aws secretsmanager create-secret  --name simple-service/magic-api-cert --secret-string file://simple-service-things/magic-api-cert.json
kubectl apply -f simple-service-things/external-secret.yaml
```

### CODE REVIEW

**Comment by silasbw** [comment]
meh, I don't know if this belongs here or at `silasbw/` or somewhere else, but I thought it was worth sharing and getting feedback on.

**Comment by JacopoDaeli** [comment]
@silasbw I like this. Let's think how to make split out. Maybe a `kes-cli` module?

**Comment by jcrugzz** [comment]
@silasbw yea a way to make this easily automaetable seems legit. 👍

**Comment by silasbw** [comment]
See https://github.com/silasbw/external-secrets-cli

**Pull request closed without merging**
